# Generated by Django 5.1.5 on 2025-02-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_tasks', models.CharField(choices=[('magazine_designs', 'No. of pages designed for Magazine'), ('professionals_issue', 'No. of professionals prepared for the issue'), ('experts_issue', 'No. of experts prepared for the issue'), ('interview_questions', 'No. of Interview questionnaire prepared & sent'), ('new_advertisers', 'No. of new advertisers found & shared'), ('crossword_puzzles', 'No. of crossword puzzles prepared')], max_length=200)),
                ('today_tasks', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NewsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_tasks', models.CharField(choices=[('news_website', 'No. of news published on Website'), ('news_socialmedia', 'No. of news published on Social Media'), ('newsletter_subscription', 'No. of subscriptions done for Newsletter'), ('email_newsletter', 'Newsletter prepared for customers via Email')], max_length=200)),
                ('today_tasks', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OthersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_tasks', models.CharField(choices=[('new_plugins', 'New Plugins designed'), ('other_tasks', 'Other tasks worked out')], max_length=200)),
                ('today_tasks', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SlidesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slides_tasks', models.CharField(choices=[('business_slides', 'No. of slides prepared for Business team'), ('new_address', 'No. of new addresses collected')], max_length=200)),
                ('today_tasks', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SocialmediaTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialmedia_tasks', models.CharField(choices=[('linkedin_connection', 'No. of connections acquired on LinkedIn'), ('twitter_connection', 'No. of connections acquired on Twitter'), ('instagram_connection', 'No. of connections acquired on Instagram'), ('facebook_connection', 'No. of connections acquired on Facebook')], max_length=200)),
                ('today_tasks', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
            ],
        ),
    ]
