# Generated by Django 5.1.5 on 2025-02-18 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_app', '0002_newstable_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazinetable',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
