# Generated by Django 5.1.5 on 2025-02-19 05:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_app', '0004_otherstable_timestamp_slidestable_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_app.newstable')),
            ],
        ),
    ]
