# Generated by Django 5.1.5 on 2025-02-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_app', '0006_magazineactivity_othersactivity_slidesactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsactivity',
            name='prev_today_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsactivity',
            name='prev_total_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
