# Generated by Django 5.1.5 on 2025-02-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_app', '0007_newsactivity_prev_today_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsactivity',
            name='prev_today_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newsactivity',
            name='prev_total_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
