# Generated by Django 5.1.5 on 2025-02-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_app', '0010_alter_newsactivity_prev_today_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazineactivity',
            name='prev_today_tasks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='magazineactivity',
            name='prev_total_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='othersactivity',
            name='prev_today_tasks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='othersactivity',
            name='prev_total_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slidesactivity',
            name='prev_today_tasks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='slidesactivity',
            name='prev_total_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaactivity',
            name='prev_today_tasks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaactivity',
            name='prev_total_tasks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
